repos:
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.2
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    files: comet-client-lib/comet_ml/**/*.py
    rev: v4.3.21
    hooks:
    -   id: isort
-   repo: https://github.com/ambv/black
    rev: 19.3b0
    files: comet-client-lib/**/*.py
    hooks:
    - id: black
      args: [--safe]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.8
    files: comet-client-lib/comet_ml/**/*.py
    hooks:
    -   id: flake8
        args: ['--config=.flake8']
        exclude: '^comet-client-lib/tests/.*$'
        additional_dependencies: ['flake8-coding==1.3.2', 'flake8-copyright==0.2.2']

python_version: python3.6
